"""
Django settings for intercom_master project.

Generated by 'django-admin startproject' using Django 1.9.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
from .common import *

DEBUG = False ALLOWED_HOSTS = ['*']
STATIC_ROOT = os.path.join(BASE_DIR, "..", "staticfiles") MEDIA_ROOT = os.path.join(BASE_DIR, "..", "media")
DATABASES = { 'default': {
'ENGINE': 'django.db.backends.postgresql', 
'NAME': 'postgres',
'USER': 'postgres',
'HOST': '127.0.0.1', },
}


