# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-06 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('first_time', models.FloatField()),
                ('first_count', models.FloatField()),
                ('first_rt', models.FloatField()),
                ('average_time', models.FloatField()),
                ('average_count', models.FloatField()),
                ('averate_rt', models.FloatField()),
                ('convo_count', models.FloatField()),
                ('array', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
                ('array', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('author', models.TextField()),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
                ('parts', models.TextField()),
                ('length', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Conversation_part',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('author', models.TextField()),
                ('created_at', models.IntegerField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('day', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('minute', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('created_at', models.IntegerField()),
                ('updated_at', models.IntegerField()),
            ],
        ),
    ]
