# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-10 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_time', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LongConvo_part',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('author', models.TextField()),
                ('created_at', models.IntegerField()),
                ('body', models.TextField()),
            ],
        ),
    ]
