# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-10 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_time', '0003_auto_20170710_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='adminId',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='admin',
            name='adminName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='admin',
            name='id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
