# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-10 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response_time', '0004_auto_20170710_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='adminId',
        ),
    ]
