# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-10 01:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response_time', '0005_remove_admin_adminid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='AdminTable',
        ),
    ]
