# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-10 02:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response_time', '0006_auto_20170710_0154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admintable',
            old_name='averageReponse',
            new_name='averageResponse',
        ),
        migrations.RenameField(
            model_name='admintable',
            old_name='firstReponse',
            new_name='firstResponse',
        ),
    ]
