# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-10 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_time', '0011_admintable_firstcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='admintable',
            name='averageResponseSum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='admintable',
            name='firstResponseSum',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='admintable',
            name='medianResponseSum',
            field=models.FloatField(default=0),
        ),
    ]
