# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-10 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_time', '0012_auto_20170710_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedconvo',
            name='author',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
