# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-10 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('response_time', '0021_mediantable'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediantable',
            name='adminLink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='response_time.AdminTable'),
        ),
        migrations.AlterField(
            model_name='mediantable',
            name='responseTime',
            field=models.FloatField(default=0),
        ),
    ]
