# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-10 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_time', '0022_auto_20170710_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedconvo',
            name='partType',
            field=models.CharField(default='comment', max_length=10),
            preserve_default=False,
        ),
    ]
