# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_time', '0023_usedconvo_parttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admintable',
            name='averageResponse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admintable',
            name='averageResponseSum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admintable',
            name='convoCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admintable',
            name='firstCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admintable',
            name='firstResponse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admintable',
            name='firstResponseSum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admintable',
            name='medianResponse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admintable',
            name='medianResponseSum',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='admintable',
            name='realCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mediantable',
            name='responseTime',
            field=models.IntegerField(default=0),
        ),
    ]
