# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-11 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response_time', '0024_auto_20170711_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admintable',
            name='array',
        ),
    ]
