# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-12 02:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('response_time', '0025_remove_admintable_array'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamTable',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('teamName', models.CharField(max_length=15)),
                ('convoCount', models.IntegerField(default=0)),
                ('realCount', models.IntegerField(default=0)),
                ('averageResponseSum', models.IntegerField(default=0)),
                ('firstCount', models.IntegerField(default=0)),
                ('firstResponseSum', models.IntegerField(default=0)),
                ('firstResponse', models.IntegerField(default=0)),
                ('averageResponse', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='admintable',
            name='teamLink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='response_time.TeamTable'),
        ),
    ]
