# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-12 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('response_time', '0026_auto_20170712_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamtable',
            name='teamName',
            field=models.CharField(max_length=20),
        ),
    ]
