# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-07-12 02:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('response_time', '0027_auto_20170712_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admintable',
            name='medianResponseSum',
        ),
    ]
